---
version: 0.1
phases:
  install:
    commands:
      - apt-get update
  pre_build:
    commands:
      - yarn install
  build:
    commands:
      - yarn run build
  post_build:
    commands:
      - aws s3 sync --delete dist/ "s3://$BUCKET_NAME"
